# Site settings
title: Your Site Title
description: A short description of your site
baseurl: "" # The subpath of your site, e.g. "/blog", leave blank for root
url: "https://yourwebsite.com" # Your domain name

# Theme settings
theme: minima # or replace with another theme name

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag

